### PR TITLE
Handle ACP connection transport failures cleanly

### LINKED ISSUE #102: Stream read failures can trigger unhandled rejections and leave pending requests unresolved
## Summary

`Connection` starts its receive loop in the background, but if the underlying stream errors, that background task can reject unhandled and any in-flight `sendRequest()` promise can remain unresolved.

This shows up in downstream transports like `acp-http-client` / `sandbox-agent` when they call `readableController.error(fetchError)` after an HTTP failure.

## Tested Version

- `@agentclientprotocol/sdk` `0.17.1`
- `zod` `4.x`
- Node.js `24.14.1`

## Minimal Repro

Copy-paste into a shell:

```bash
tmpdir=$(mktemp -d)
cd "$tmpdir"

npm init -y >/dev/null
npm install @agentclientprotocol/sdk@0.17.1 zod@4 >/dev/null

cat > repro.mjs <<'REPRO'
import { ClientSideConnection } from "@agentclientprotocol/sdk";

let controller;

process.on("unhandledRejection", (err) => {
  console.log("unhandledRejection:", err?.message ?? String(err));
});

const connection = new ClientSideConnection(
  () => ({
    async writeTextFile() {
      return {};
    },
    async readTextFile() {
      return { content: "x" };
    },
    async requestPermission() {
      return {
        outcome: {
          outcome: "selected",
          optionId: "allow",
        },
      };
    },
    async sessionUpdate() {},
  }),
  {
    readable: new ReadableStream({
      start(c) {
        controller = c;
      },
    }),
    writable: new WritableStream({
      async write() {},
    }),
  },
);

const pending = connection.newSession({
  cwd: "/tmp",
  mcpServers: [],
});

controller.error(new Error("stream exploded"));
console.log("controller.error returned");

const outcome = await Promise.race([
  pending.then(
    () => "resolved",
    (err) => `rejected:${err?.message ?? String(err)}`,
  ),
  new Promise((resolve) => setTimeout(() => resolve("timeout"), 50)),
]);

console.log("pending outcome:", outcome);

await new Promise((resolve) => setTimeout(resolve, 50));
REPRO

node repro.mjs
```

## Actual Output

```text
controller.error returned
unhandledRejection: stream exploded
pending outcome: timeout
```

## Why This Is Bad

Two things happen after the stream errors:

1. the receive loop rejection escapes as an `unhandledRejection`
2. the pending `newSession()` request never resolves or rejects

In stricter Node settings this can crash the process:

```bash
node --unhandled-rejections=strict repro.mjs
```

That exits non-zero and crashes with `Error: stream exploded`.

## Expected Behavior

When the stream errors, the connection should:

- catch the background receive-loop failure
- close/abort the connection cleanly
- reject all pending request promises with the transport error
- avoid any unhandled rejection from the background receive loop

## Likely Fix Area

`Connection` currently starts `#receive()` in the constructor without attaching a catch, and it does not reject pending responses when the stream closes with an error.

A fix that worked locally was:

- attach a catch to the background `#receive()` task
- centralize close handling
- reject `#pendingResponses` on stream failure
- add a regression test for `ReadableStreamDefaultController.error(...)`

### PR DESCRIPTION
**Pull request by advait**
## Summary

Fixes #102.

When the underlying ACP stream errors, `Connection` currently leaves in-flight requests unresolved and can surface the stream failure as an unhandled rejection from the background receive loop.

This change:

- routes readable-stream failures through normal connection close handling
- rejects pending request promises when the connection closes with a transport error
- adds a regression test for `ReadableStreamDefaultController.error(...)`

## Notes

- keeps transport failures silent in the SDK itself rather than logging from the library
- keeps the shared JSON-RPC types unchanged; the transport-error rejection handling stays internal to `acp.ts`

## Validation

- `npm run build`
- `npm test`

### CODE REVIEW

File: src/acp.ts [hunk 1]
```diff
@@ -11,11 +11,15 @@ import type {
...
   ErrorResponse,
-  PendingResponse,
   RequestHandler,
   NotificationHandler,
 } from "./jsonrpc.js";
 
+type ConnectionPendingResponse = {
+  resolve: (response: unknown) => void;
+  reject: (error: unknown) => void;
+};
```
Comment (advait) [inline src/acp.ts:21]: `PendingResponse` is protocol-shaped: it only covers JSON-RPC error responses.

`ConnectionPendingResponse` is connection-shaped: on stream shutdown we may need to reject with a raw transport error before any JSON-RPC envelope exists. Decided to keep that broader type local to `acp.ts` to avoid widening the shared protocol types.

**Comment by benbrandt** [comment]
Thanks for looking into this! After a few rounds of review, I tried to clean up a few more cases this revealed, but would be curious to get your take on it!

**Comment by advait** [comment]
@benbrandt LGTM thanks!
